Feature/add users card bl
YarynaBas1234/users-app pull request #17
Opened 2021-12-21 14:49 UTC by YarynaBas1234

2021-12-21 15:22 UTC, illia-nerdysoft requested changes

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +const Data = styled(H5)`
bad naming

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +const UserName = styled(H4)`
bad naming

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +  item: IUser;
item - bad naming. use appropriate namings

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +  margin-right: 8px;
try to avoid right margins

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/translations/ua.json
> +      "EMAIL": "логін: ",
i guess, that here is bad translation

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/containers/Home/Home.tsx
> +      {users?.map(item => {
move it to the separate constant, use appropriate hook and simplify this

2021-12-21 15:22 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +  margin: 16px 16px 0 0;
use left margin instead of right

2021-12-22 09:57 UTC, illia-nerdysoft requested changes

2021-12-22 09:57 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +const UserData = styled(H5)`
Bad naming

2021-12-22 09:57 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +const UserDataWrapper = styled(H5)`
Bad naming

2021-12-22 09:57 UTC, illia-nerdysoft commented on src/containers/Home/Home.tsx
> +      {CreateUsersCard}
Bad naming

2021-12-22 09:57 UTC, illia-nerdysoft commented on src/containers/Home/index.tsx
> +  return <Home CreateUsersCard={CreateUsersCard}/>;
Bad naming

2021-12-22 12:14 UTC, illia-nerdysoft requested changes

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/Card.tsx
> +      <UsersDataWrapper>
move to the new component and rename inner components

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/Home.tsx
> +  createUsersCard: JSX.Element[] | undefined;
you can simplify this

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/Home.tsx
> +  createUsersCard: JSX.Element[] | undefined;
React.ReactElement

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/Home.tsx
> +  createUsersCard: JSX.Element[] | undefined;
use only one element instead of array

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/Home.tsx
> +  createUsersCard: JSX.Element[] | undefined;
rename appropriate to the type

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/index.tsx
> +  const createUsersCard = React.useMemo(() => {
read about use memo

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/index.tsx
> +  const createUsersCard = React.useMemo(() => {
JSX should not be in the index file. move in inside container

2021-12-22 12:14 UTC, illia-nerdysoft commented on src/containers/Home/index.tsx
> +    return users?.map((user: IUser) => <Card key={user.id} user={user} />);
return only one element here

2021-12-23 09:28 UTC, ArturFFor approved these changes

2021-12-23 09:31 UTC, merged